"""making cpf and email unique

Revision ID: 43c535b68ee4
Revises: 47fff897f778
Create Date: 2025-02-13 23:26:03.681903

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "43c535b68ee4"
down_revision: Union[str, None] = "47fff897f778"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "participant", ["email"])
    op.create_unique_constraint(None, "participant", ["cpf"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "participant", type_="unique")
    op.drop_constraint(None, "participant", type_="unique")
    # ### end Alembic commands ###
