"""creating initial tables

Revision ID: 47fff897f778
Revises:
Create Date: 2025-02-12 17:36:19.679640

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "47fff897f778"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "participant",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("cpf", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("phone", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "raffle",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("edition", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=False),
        sa.Column("total_tickets", sa.Integer(), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("edition"),
    )
    op.create_table(
        "prize",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("raffle_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=False),
        sa.Column("is_main", sa.Boolean(), nullable=False),
        sa.Column("drawn_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["raffle_id"],
            ["raffle.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ticket",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("raffle_id", sa.Integer(), nullable=False),
        sa.Column("prize_id", sa.Integer(), nullable=True),
        sa.Column("participant_id", sa.Integer(), nullable=True),
        sa.Column("number", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("purchased_in", sa.DateTime(), nullable=True),
        sa.Column("is_drawn", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["participant_id"],
            ["participant.id"],
        ),
        sa.ForeignKeyConstraint(
            ["prize_id"],
            ["prize.id"],
        ),
        sa.ForeignKeyConstraint(
            ["raffle_id"],
            ["raffle.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ticket")
    op.drop_table("prize")
    op.drop_table("raffle")
    op.drop_table("participant")
    # ### end Alembic commands ###
